# Docker Compose for Rehome Development
services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rehome-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=rehome
      - DB_USERNAME=rehome
      - DB_PASSWORD=rehome_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - SESSION_DRIVER=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - mysql
      - redis
    networks:
      - rehome

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rehome-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - rehome

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: rehome-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=rehome
      - MYSQL_USER=rehome
      - MYSQL_PASSWORD=rehome_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - rehome

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rehome-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rehome

  # Mailhog for Email Testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: rehome-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - rehome

  # PhpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: rehome-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    depends_on:
      - mysql
    networks:
      - rehome

# Named Volumes
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  backend_storage:
    driver: local

# Networks
networks:
  rehome:
    driver: bridge