# Development Docker Compose Override
services:
  # Laravel Backend - Development Configuration
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
      - backend_storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key-here
      - COMPOSER_ALLOW_SUPERUSER=1
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Next.js Frontend - Development Configuration  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    command: pnpm dev

  # Storybook for Component Development
  storybook:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rehome-storybook
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm storybook
    networks:
      - rehome

volumes:
  backend_vendor:
  frontend_node_modules: